services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file: ./django/.env.production
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - /opt/system/apps:/opt/system/apps  # フロント静的ファイル
    depends_on:
      - django
    restart: always
